architecture-beta
%% this is still wip
    group api(cloud)[API]
    group ams(mdi:calendar)[AMS]

    service crud(mdi:transfer)[CRUD Schedules] in ams
    service schedules(mdi:database-outline)[Schedule Database]

    service db(database)[Database] in api
    service disk1(disk)[Storage] in api
    service disk2(disk)[Storage] in api
    service server(server)[Server] in api

    db:L -- R:server
    disk1:T -- B:server
    disk2:T -- B:db
    
    crud:R -- L:schedules